### ISSUE TITLE
L1D piston brake completely prevents recoil

### ISSUE THREAD

**Issue by bszafian** [gdtk-uq/gdtk#17]
Hi all,

I am simulating a shock tunnel (HEG) using L1D. For this specific condition the piston used is equipped with brakes, that are automatically applied when the piston is moving backwards. 

I have experimental data showing the piston does have some recoil even with the brakes equipped.

However, in the L1D simulation, the piston is stopped completely at the moment of the would-be recoil. Changing the brakes friction force has no effect on this behavior.

I'd really appreciate some help with this! 

Thanks!
Cheers,
Balazs from DLR Göttingen

**Comment by pajacobs-ghub** [comment]
Balazs,
Can you send me your scripts for the case that is not working as you expect?  I would have to look at the numbers during the simulation to work out what's going on.  The behaviour that you describe is not what I expect.  

A cut-down simulation, with just the compression tube, pushing gas and piston will suffice.

Cheers,
Peter J.

**Comment by bszafian** [comment]
Peter,

I've attached the parameter file of a cut-down simulation.

[param_file.txt](https://github.com/gdtk-uq/gdtk/files/9829879/param_file.txt)

Cheers,
Balazs

**Comment by bszafian** [comment]
Hi Peter,

do you need any more information, or is this parameter file enough? I'd be happy to send graphs as well, if needed.

Cheers,
Balazs

**Comment by bszafian** [comment]
Hi Peter,

Just to let you know, I ran a couple of simulations with an older version of L1d, and the same behavior was observed; the piston stopping completely at the would be recoil position.

Cheers,
Balazs

**Comment by pajacobs-ghub** [comment]
Fixed in rev. 2c6582ff

Attached are files for Balazs' example modified to close the right-end of the compression tube plugged so that the piston is forced back upstream.
![brakes-slipping-heg](https://github.com/gdtk-uq/gdtk/assets/62410919/0e6d4012-3910-42aa-87d2-12c1b5bc4e2c)
[brakes-py.txt](https://github.com/gdtk-uq/gdtk/files/13698028/brakes-py.txt)
[brakes-run-sh.txt](https://github.com/gdtk-uq/gdtk/files/13698029/brakes-run-sh.txt)
[prepare-gas-files -sh.txt](https://github.com/gdtk-uq/gdtk/files/13698030/prepare-gas-files.-sh.txt)
