### ISSUE TITLE
Questions about source code quote

### ISSUE THREAD

**Issue by KulaLAForU** [gdtk-uq/gdtk#57]
Hi,

The problem I'm having really makes me despair, please forgive my rookie coding skill.
I changed the folloing code in reaction.d to use Park's constants for equilibruim :
<img width="1345" alt="Screenshot 2024-04-02 at 04 31 12" src="https://github.com/gdtk-uq/gdtk/assets/40930186/1e0427f7-8ae6-49d6-b77b-cc7201b60901">
And then in reaction.lua I changed here:
<img width="481" alt="Screenshot 2024-04-02 at 04 30 58" src="https://github.com/gdtk-uq/gdtk/assets/40930186/a94f9065-8e15-4fca-871f-60ba98745d64">
<img width="1632" alt="Screenshot 2024-04-02 at 04 34 53" src="https://github.com/gdtk-uq/gdtk/assets/40930186/4133afa7-2eab-4788-8b4f-35862c3f473b">
Finally I changed rate_constant.d :
<img width="1460" alt="Screenshot 2024-04-02 at 04 36 02" src="https://github.com/gdtk-uq/gdtk/assets/40930186/7012cb89-3374-42c9-899c-b4f87076e7cc">

But,, how can I quote A1, A2, A3, A4, A5 as  
<img width="1274" alt="Screenshot 2024-04-02 at 04 36 47" src="https://github.com/gdtk-uq/gdtk/assets/40930186/9071aecb-4b1b-4e0a-b763-e215c4ba2998">

Sincerely thanks for your help,
have a good day,
Jianshu Wu

**Comment by rjgollan-on-github** [comment]
Hi Jianshu,
I can point to the problem. Your "A1", "A2", etc values are given to a model for the rate constant. Due to our use of classes to encapsulate the concerns of various interacting parts, the "A1", "A2" values are NOT available when you attempt to call them in a reaction. The reaction needs only know about functions for k_f, k_b, K_eq etc. It does not know the details of the internals for those objects. Your constants are internal details.

I have some better suggestions for you.

1. Don't use the Park equilibrium constant. It's too specific to one particular chemistry. This is why I have never implemented it. Why do you want to use Park so much? I prefer to use the general equilibrium constant computed from Gibbs free energy.
2. If you really want the effect of the Park equilibrium constant, I would reverse engineer it. Outside the code, you could compute a bunch of k_b values based on k_f and K_eq_Park for a range of temperatures. Then using a fitting package, fit an Arrhenius form to your k_b. You should be able to control the error. Then you can use those Arrhenius parameters in the br={'Arrhenius', ... etc.}

**Comment by rjgollan-on-github** [comment]
Hi Jianshu,
My point is that using a fit to k_b *does* allow you to compare, but without modifying internal source code. Instead, you can just provide the appropriate backwards rate parameters to achieve the same effect. I think you could plot the actual k_b and your fit k_b and compare. I doubt any fitting discrepancy would propagate through as a discernible change in shock location.

If you do want to modify source code, I looked over our code. We do not provide an easy way to specialise the computation of equilibrium constant. There is only function and it presently cannot be substituted.

If you really want to try the direct computation of equilibrium constant as per Park, then I suggest a hard-code override in reaction.d. Replace the K_eq value with your computed K_eq value. Be sure to check units. You need an equilibrium constant based on concentrations, not on pressure. There are various definitions in the literature.

But, as mentioned above, I think the building of "effective" k_b curves is the least pain path and involves no source code modification, only modification to your chemistry input file.

**Comment by KulaLAForU** [comment]
Thanks very much Rowan, 

This amazing software really great but I do want to change a little bit in source code, I'm learning D langguage a bit deeper to do so. 

And appreciate about your advice about the chemistry input file, I'll read and learn that part too.

Have a good day / night

**Comment by KulaLAForU** [comment]
Hi, 

I suddenly realized we would be meeting at the HiSST next week, so small world...... If you don't mind I'd like to say hello then. 

Have a safe trip
