### ISSUE TITLE
Mismatch of Number of grid points between original (.su2) grid file and post-processed (.pvtu) files in multiblock simulation

### ISSUE THREAD

**Issue by blackysak** [gdtk-uq/gdtk#58]
Hi,
I tried running multi-block steady flow simulations of SBLI. I partitioned .su2 grid file using ugrid_partition command. I ran the simulation the multi-block. After post-processing, I have checked the number of grid points in the original grid .su2 file and the post-processed (.pvtu) file. However, number of cells remains same in both the files.

For example in my case:
In .su2 grid file, No of cellls: 99,008; No of points: 50,040
In .pvtu file, No of cellls: 99,008; No of points: 51,197

When I run the same problem with single block, number of points are same in both files.

Single block:
![single](https://github.com/gdtk-uq/gdtk/assets/30336783/92f3b59a-351f-45bf-87e8-50c8dd1300c8)

Multiblock:
![multi](https://github.com/gdtk-uq/gdtk/assets/30336783/223ab5ee-57fc-4b58-9626-aa7af245bff5)

So, I am wondering the ghost points information are also written in the post-process files. Is that true?
**Is there anyway I can match the number of points in both the files?** 
I am doing grid adaptation. So matching the number of grid points in these two file is essential. 

Please let me know.

Thanks.
Sakthi

**Comment by kyleadm** [comment]
Hi Sakthi,

The discrepancy in the number of points between the single-block simulation and multi-block simulation arises due to the presence of duplicate points along the block-block boundaries in the multi-block simulation. Essentially, each block in the multi-block simulation has its own version of the shared points present along a block-block boundary. As a result, each block's .su2 and .vtu files have a definition of the shared points. The .pvtu file serves as a parent file for the .vtu files. On opening the .pvtu file in Paraview, all the .vtu files are opened, which leads to the points along the block-block boundaries being counted twice in the summary provided by Paraview.

Kyle.

**Comment by blackysak** [comment]
Hi Kyle,
Thanks for the clarification. Is there any way we can eliminate these duplicate points? If I merger blocks still the numbers are same.


Thanks.

**Comment by kyleadm** [comment]
Hi Satki,

If you need to have no duplicate points when you are visualizing the simulation in Paraview, then I recommend the following steps:

1. open the .pvd file (NOT the .pvtu file)
2. apply the Merge Blocks filter (Filters/Alphabetical/Merge Blocks)

This will merge the blocks and remove the duplicate points, the # of points should now match the single block representation.

Kyle.

**Comment by uqngibbo** [comment]
Any progress on this @blackysak ?
