### ISSUE TITLE
Boundary layer velocity

### ISSUE THREAD

**Issue by jr144393** [gdtk-uq/gdtk#68]
I have noticed some discrepancies with the velocity profile here, for the NoSlip wall condition, WallBC_NoSlip_FixedT, the velocity at the wall seems far from zero. 

This is the paraview result: 

![question1](https://github.com/user-attachments/assets/1dde5b9e-a4a6-40b8-b0e1-828e916a16e8)

And the settings for that wall: 

![question2](https://github.com/user-attachments/assets/98a3021d-bbd5-4a45-92ce-9520223c5e73)

![question3](https://github.com/user-attachments/assets/5ef7cc1d-f8b6-487d-9839-e1ad98a63fab)

Any comments on why this might be so far off? The resolution is not to the proper settings, but wouldn't the velocity at the same resolution still have the velocity at the wall set to zero?

**Comment by jr144393** [comment]
Also, I suppose its important to mention this setting is on: 

![question4](https://github.com/user-attachments/assets/c1a446ab-c4de-4c03-ada2-0f058539c012)

**Comment by pajacobs-ghub** [comment]
What you show in the first image is the average velocity for the cell, so no the wall velocity.  What is your free-stream velocity?

**Comment by uqngibbo** [comment]
Hi jr,

As PJ said, we don't expect the first cell to actually be zero, since the no-slip condition is applied at the actual interface representing the wall. That said, 541 m/s is a pretty large number.

Tightening the grid clustering to the wall should reduce this number to something more reasonable. You may want to try using the Geometric Cluster function:
https://gdtk.uqcloud.net/docs/eilmer/eilmer-reference-manual/#_geometric_function
