### ISSUE TITLE
Quesstion on source code input

### ISSUE THREAD

**Issue by KulaLAForU** [gdtk-uq/gdtk#84]
Hi,

Recently I added a diffusion part in gdtk/src/kinetics/energy_exchange_mechanism.d class LT line 96th : 
double M_1 = 9.176137;
        number T_sh = ((2*1.4*M_1*M_1 - (1.4-1)) * ((1.4-1)*M_1*M_1 + 2) / ((1.4+1)*(1.4+1)*M_1*M_1)) * 293.0;
        // number T_sh = 6500.0;
        number s = 3.5*exp(-5000.0/T_sh);
        return gs.massf[m_p] * (evStar - ev)  * (pow(fabs((T_sh - gs.T_modes[0])/(T_sh - 293.0)), s-1.0)) / m_tau;
The results work fine for me so I wondering is possible to add M_1 as an automatic parameter as the initial free stream condition?

Thank you very much!!
Jianshu Wu

**Comment by rjgollan-on-github** [comment]
Hi Jianshu,

The answer is "not easily". I usually dislike these models that tie a kinetic quantity to a flow quantity, because they break our coding practice of separation of concerns.

You could make the M1 parameter configurable in the input files related to the energy exchange.

But linking it to the inflow condition creates problems. We don't have a singleton inflow condition. Some simulations might have multiple inflows and some might do inflow in different manners than a simple SupersonicInflow_BC. It would be difficult to write code to pick up all possible ways that M1 might be set.

**Comment by KulaLAForU** [comment]
Thank you professor, then I'll just manually change the source code each time I run a different case.

Have a good day!
