### ISSUE TITLE
NENZF1d python question and imporvement request.

### ISSUE THREAD

**Issue by UNSWHilbert** [gdtk-uq/gdtk#87]
Hi GDTK team, 

I have been working to get NENZF1d to work. I have one question and one potential improvement idea. 

The docs for NENZF1d  talk about how cea2 is required for the code to work, but there is no detailed explanation on where the files need to go. I needed to go to the source code to work it out. Therefore it would be great if that can be included in the docs next time they are being edited. 

I have also been playing with the python version of nenz1f and I am struggling to get it to work. My main struggle is around importing the gas dynamics models. The example has the following for the models: 

gas_model_1 = "air-5sp-eq.lua"
gas_model_2 = "air-5sp-1T.lua"
reactions = "air-5sp-1T-reactions.lua"

This fails on my machine since it isn't able to find those files. If I than try it with the full path it still fails:
gas_model_1 = "/home/user/Documents/TADFA/air-5sp-eq.lua"
gas_model_2 = "/home/user/Documents/TADFA/air-5sp-1T.lua"
reactions = "/home/user/Documents/TADFA/air-5sp-1T-reactions.lua"

It fails with: "cannot open air-5sp-1T.lua: No such file or directory"
It therefore seems like the gas_model_2 variable is not being read and is set to some constant. Any ideas on how I should go about getting it work?

Cheers,
Hilbert

**Comment by uqngibbo** [comment]
Hi Hilbert,

Thanks for the feedback on this. We're actually in the process of moving away from CEA, and using our in-house tool for equilibrium chemistry instead. Once that move is complete we won't require any special install instructions anymore.

You can actually try this already: t4m8-11742.yaml in the examples directory uses:
```
gas-model-1: air-5sp-eq.lua
```

Instead of 
```
gas-model-1: cea-air5species-gas-model.lua
```


For the python version, there does seem to be something strange going on with the file paths. I found a work around where you have to run the python interpreter from the same directory as the gas files. For example, if I change the python script to:
```
gas_model_1 = "/home/uqngibbo/air-5sp-eq.lua"
gas_model_2 = "/home/uqngibbo/air-5sp-1T.lua"
reactions = "/home/uqngibbo/air-5sp-1T-reactions.lua"
```

Then running from the examples directory fails:
```
uqngibbo@melchior:~/source/gdtk/examples/nenzf1d$ python3 py-t4m8-11742.py 
got libpath:  /home/uqngibbo/programs/gdtk/master/lib/libnenzf1d.so
Caught exception in cwrap.run, message was:
cannot open air-5sp-1T.lua: No such file or directory
```

But if I move to where the files are:
```
uqngibbo@melchior:~$ python3 ~/source/gdtk/examples/nenzf1d/py-t4m8-11742.py                                            
got libpath:  /home/uqngibbo/programs/gdtk/master/lib/libnenzf1d.so
Initial gas in shock tube (state 1).
  pressure    192 kPa       
  density     2.22072 kg/m^3
  temperature 300 K                                                                                                    
  H1          0.00187107 MJ/kg
```

I will have a look at this, but in the meantime you should be able to work around it.
