### ISSUE TITLE
Gas-user-guide thermally perfect gas - typo

### ISSUE THREAD

**Issue by lift-cmyk** [gdtk-uq/gdtk#91]
In the gas-user-guide, on page 23, under section 5.1, to initialize a thermally perfect gas it is said that:

> Note that the particular value of pressure is not important because the properties of Cp and h are not functions of temperature in a thermally perfect gas.

I believe it is supposed to mean that Cp and h are not functions of pressure in a thermally perfect gas, and temperature is just a typo here. Is that correct?

**Comment by uqngibbo** [comment]
Yes this is a typo. Thanks for finding that. I'll get it fixed.
________________________________
From: lift-cmyk ***@***.***>
Sent: Thursday, 19 December 2024 5:23 PM
To: gdtk-uq/gdtk ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gdtk-uq/gdtk] Gas-user-guide thermally perfect gas - typo (Issue #91)


In the gas-user-guide, on page 23, under section 5.1, to initialize a thermally perfect gas it is said that:

Note that the particular value of pressure is not important because the properties of Cp and h are not functions of temperature in a thermally perfect gas.

I believe it is supposed to mean that Cp and h are not functions of pressure in a thermally perfect gas, and temperature is just a typo here. Is that correct?
